//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.30 at 06:34:04 PM CEST 
//


package org.yamcs.studio.ui.commanding.stack.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="command" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="commandArgument" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="argumentName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="argumentValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="commandName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "command"
})
@XmlRootElement(name = "commandStack")
public class CommandStack {

    @XmlElement(required = true)
    protected List<CommandStack.Command> command;

    /**
     * Gets the value of the command property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the command property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommand().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommandStack.Command }
     * 
     * 
     */
    public List<CommandStack.Command> getCommand() {
        if (command == null) {
            command = new ArrayList<CommandStack.Command>();
        }
        return this.command;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="commandArgument" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="argumentName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="argumentValue" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="commandName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "commandArgument"
    })
    public static class Command {

        protected List<CommandStack.Command.CommandArgument> commandArgument;
        @XmlAttribute(name = "commandName")
        protected String commandName;

        /**
         * Gets the value of the commandArgument property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the commandArgument property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCommandArgument().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CommandStack.Command.CommandArgument }
         * 
         * 
         */
        public List<CommandStack.Command.CommandArgument> getCommandArgument() {
            if (commandArgument == null) {
                commandArgument = new ArrayList<CommandStack.Command.CommandArgument>();
            }
            return this.commandArgument;
        }

        /**
         * Gets the value of the commandName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCommandName() {
            return commandName;
        }

        /**
         * Sets the value of the commandName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCommandName(String value) {
            this.commandName = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="argumentName" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="argumentValue" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class CommandArgument {

            @XmlAttribute(name = "argumentName")
            protected String argumentName;
            @XmlAttribute(name = "argumentValue")
            protected String argumentValue;

            /**
             * Gets the value of the argumentName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getArgumentName() {
                return argumentName;
            }

            /**
             * Sets the value of the argumentName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setArgumentName(String value) {
                this.argumentName = value;
            }

            /**
             * Gets the value of the argumentValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getArgumentValue() {
                return argumentValue;
            }

            /**
             * Sets the value of the argumentValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setArgumentValue(String value) {
                this.argumentValue = value;
            }

        }

    }

}
