//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.30 at 06:34:04 PM CEST 
//


package org.yamcs.studio.ui.commanding.stack.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.yamcs.studio.ui.commanding.stack.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.yamcs.studio.ui.commanding.stack.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CommandStack }
     * 
     */
    public CommandStack createCommandStack() {
        return new CommandStack();
    }

    /**
     * Create an instance of {@link CommandStack.Command }
     * 
     */
    public CommandStack.Command createCommandStackCommand() {
        return new CommandStack.Command();
    }

    /**
     * Create an instance of {@link CommandStack.Command.CommandArgument }
     * 
     */
    public CommandStack.Command.CommandArgument createCommandStackCommandCommandArgument() {
        return new CommandStack.Command.CommandArgument();
    }

}
