/*
 * generated by Xtext
 */
package org.csstudio.yamcs.ycl.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class YCLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/csstudio/yamcs/ycl/dsl/parser/antlr/internal/InternalYCL.tokens");
	}
}
