/*
 * generated by Xtext
 */
package org.csstudio.yamcs.ycl.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.csstudio.yamcs.ycl.dsl.services.YCLGrammarAccess;

public class YCLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private YCLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.csstudio.yamcs.ycl.dsl.parser.antlr.internal.InternalYCLParser createParser(XtextTokenStream stream) {
		return new org.csstudio.yamcs.ycl.dsl.parser.antlr.internal.InternalYCLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public YCLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(YCLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
