/********************************************************************************
 * Copyright (c) 2010 ITER Organization and others
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 ********************************************************************************/
package org.csstudio.utility.batik;

import org.eclipse.swt.graphics.Image;

/**
 * Listener of {@link SVGHandler} to be notified of images generated by the {@link UpdateManager} i.e. when an animated
 * SVG file with animation started is specified.
 */
public interface SVGHandlerListener {

    /**
     * In case of animated SVG, notifies when a new {@link Image} is available. {@link SVGHandler} is responsible of
     * images disposal. For practical reason, this method is invoked in the UI thread.
     *
     * @param image,
     *            new image to display.
     */
    public void newImage(Image image);
}
