/*
 * generated by Xtext
 */
package org.yamcs.studio.ycl.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.yamcs.studio.ycl.dsl.ui.internal.YCLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class YCLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return YCLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return YCLActivator.getInstance().getInjector(YCLActivator.ORG_YAMCS_STUDIO_YCL_DSL_YCL);
	}
	
}
