/*
* generated by Xtext
*/
package org.csstudio.yamcs.ycl.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class YCLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.csstudio.yamcs.ycl.dsl.ui.internal.YCLActivator.getInstance().getInjector("org.csstudio.yamcs.ycl.dsl.YCL");
	}
	
}
